### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/mozitahub_bot#11]
Mancano delle cose da fare, creo una lista, man mano che tutti voi vi prenotate o scrivete nelle issue associate la aggiorno:
- [ ] TODO: URGENTE! gestire i callback -> ogni bottone quando lo si clicca, ad eccezione degli URL produce un callback, cioe' una stringa di testo che identifica un bottone. Bisogna gestire quella stringa di testo e richiamare la funzione di visualizzazione del corretto messaggio (es. "/help" -> richiama il comando /help) #5 
- [ ] TODO: creare un nuovo database con le frasi che attualmente sono in JSON? (puo essere una buona idea, ma bisogna valutare) #7 
- [ ] TODO: comando vademecum, in quanto prima i file erano salvati localmente in una cartella, bisogna inventarsi un modo per auto aggiornarli cosi non dobbiamo aggiornarli ogni volta #8 
- [ ] TODO: gestire la parte admin -> creare funzioni e quant'altro, definire le nuove funzioni (quelle vecchie venivano gestite da uno spazio, valutare se gestirle anche stavolta tramite spazio oppure fare una cosa un po piu' interattiva e creare dei bottoni, ogni bottone ha il suo testo e gestisce una cosa diversa) #9 
Esempio:
![immagine](https://user-images.githubusercontent.com/44711271/97293391-e5633f80-184c-11eb-9c96-3a3197aed300.png)

N.B. alcune istruzioni prima venivano usate per gestire i file json: ora devono fare le query nel db insert, delete, update
- [ ] TODO: modificare le stringhe -> togliere i nomi delle variabili li, aggiungerle nel codice mediante .format(var1, varN) (alcune parti non sono state sviluppate, occhio a cosa si modifica) #7 

Questi TODO sono anche nel codice, cosi man mano si possono togliere e aggiornare!

**Comment by Sav22999** [comment]
Basandomi sul diagramma. Cosa dovrebbe fare nel caso in cui il "Check: messaggio vuoto" sia negativo/positivo?

Questa soluzione, comunque, non è applicabile. C'è il problema che quando riavvii lo script (per un aggiornamento, ad esempio), il bot non potrebbe più modificare i messaggi inviati precedentemente al riavvio. Quindi si avrebbe una chat confusionaria

**Comment by dag7dev** [comment]
@Sav22999 ovviamente se il messaggio è vuoto invierà un messaggio dicendo "il messaggio è vuoto"

Non ho capito cosa intendi...perché dovrei modificar i messaggi precedentemente inviati al riavvio?

**Comment by Sav22999** [comment]
Per mostrare il menu principale. Oppure intendi "append" ai messaggi già esistenti?

**Comment by Sav22999** [comment]
Per mostrare il menu principale. Oppure intendi "append" ai messaggi già esistenti?

**Comment by dag7dev** [comment]
Append
